name: CI/CD Pipeline for HolaMundoMultilenguaje

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Configuración de SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Verificar conexión antes de continuar
          ssh -o BatchMode=yes -o ConnectTimeout=5 $USERNAME@$HOST "echo '✅ Conexión SSH exitosa'" || exit 1

          # Crear directorio de despliegue si no existe
          ssh $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"

          # Sincronizar archivos con el servidor
          rsync -avz --delete --exclude 'tests' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH

          # Ejecutar Composer install en el servidor
          ssh $USERNAME@$HOST "cd $DEPLOY_PATH && composer install --no-dev --optimize-autoloader"

          # Reiniciar Apache sin pedir contraseña
          ssh $USERNAME@$HOST "echo '$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl restart apache2' | sudo tee /etc/sudoers.d/$USERNAME"
          ssh $USERNAME@$HOST "sudo systemctl restart apache2"
